// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eFoodDelivery_API.DbContexts;

#nullable disable

namespace eFoodDelivery_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230424133003_m12-updating-images-container")]
    partial class m12updatingimagescontainer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dlk_efooddelivery_api")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("dlk_roles", "dlk_efooddelivery_api");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("dlk_role_claim", "dlk_efooddelivery_api");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dlk_user_claim", "dlk_efooddelivery_api");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("dlk_user_login", "dlk_efooddelivery_api");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("dlk_user_roles", "dlk_efooddelivery_api");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("dlk_user_tokens", "dlk_efooddelivery_api");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Md_uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("dwh_cart", "dwh_efooddelivery_api");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartId");

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Md_uuid");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("dwh_cartItem", "dwh_efooddelivery_api");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientEmail");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ClientId");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientName");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientPhone");

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Md_uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrderDate");

                    b.Property<string>("OrderPaymentID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderPaymentID");

                    b.Property<int>("OrderQuantityItems")
                        .HasColumnType("int")
                        .HasColumnName("OrderQuantityItems");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderStatus");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float")
                        .HasColumnName("OrderTotal");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("dwh_order", "dwh_efooddelivery_api");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemName");

                    b.Property<double>("ItemPrice")
                        .HasColumnType("float")
                        .HasColumnName("ItemPrice");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int")
                        .HasColumnName("ItemQuantity");

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Md_uuid");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderId");

                    b.HasKey("OrderDetailsId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("dwh_orderDetails", "dwh_efooddelivery_api");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Md_uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("Price");

                    b.Property<string>("Tag")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tag");

                    b.HasKey("Id");

                    b.ToTable("dwh_product", "dwh_efooddelivery_api");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Almuerzo",
                            Description = "Receta de cocina con base de arroz, con origen en la actual Comunidad Valenciana, hoy en día muy popular en toda España y servida en restaurantes de todo el mundo.​",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/1.paella-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5665),
                            Md_uuid = new Guid("501bd70b-6d50-4706-8c26-640ab79bd3f9"),
                            Name = "Paella Valenciana",
                            Price = 9.9499999999999993,
                            Tag = "Mejor valorados"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Almuerzo",
                            Description = "Tortilla u omelet ​ a la que se le agrega patatas troceadas.​ Se trata de uno de los platos más conocidos y emblemáticos de la cocina española.​",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/2.tortilla-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5674),
                            Md_uuid = new Guid("33a344db-ce9e-44a8-9f58-8b4b69eefb32"),
                            Name = "Tortilla de Patatas",
                            Price = 7.9900000000000002,
                            Tag = "Más vendidos"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Almuerzo",
                            Description = "​El salmorejo cordobés es una crema servida habitualmente como primer plato. Se elabora mediante una cierta cantidad de miga de pan,​ a la que se le incluye además ajo, aceite de oliva, sal y tomates.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/3.salmorejo-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5692),
                            Md_uuid = new Guid("7f919663-bf5e-4799-bc10-0b6985bd48bc"),
                            Name = "Salmorejo Cordobés",
                            Price = 6.4900000000000002,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Almuerzo",
                            Description = "​Conjunto de hortalizas cocidas con unos aditamentos de carne, pescado y ave condimentada con una salsa mayonesa\", donde la remolacha, las judías verdes y las alcaparras forman parte de la receta.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/4.ensaladilla-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5698),
                            Md_uuid = new Guid("a87fa6f6-aeb0-4a10-b974-bc000f7e1b40"),
                            Name = "Ensaladilla Rusa",
                            Price = 5.9500000000000002,
                            Tag = "Más vendidos"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Almuerzo",
                            Description = "​Preparación culinaria de España y Portugal habitual de la gente que se dedica a la trashumancia española. Se elabora principalmente con pedazos de la miga de pan tostado acompañados de carnes y verduras.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/5.migas-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5752),
                            Md_uuid = new Guid("893dd8a3-5a76-4981-8360-901d3c11fed8"),
                            Name = "Migas Manchegas",
                            Price = 10.99,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Cena",
                            Description = "​Se sirven generalmente como una tapa en muchos bares, o como raciones. Como algunos otros platos de marisco se suelen servir junto con una rodaja de limón.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/6.calamares-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5759),
                            Md_uuid = new Guid("e8fcfd0d-1700-4c4b-846e-fc0b994a79bd"),
                            Name = "Calamares a la Romana",
                            Price = 8.75,
                            Tag = "Mejor valorados"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Cena",
                            Description = "​Se trata de un plato festivo elaborado con pulpo cocido entero (generalmente en ollas de cobre) que está presente en las fiestas, ferias y romerías de Galicia.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/7.pulpo-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5768),
                            Md_uuid = new Guid("36220a7a-fe79-4e88-81f3-feaebcbb1093"),
                            Name = "Pulpo a la Gallega",
                            Price = 8.5,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Almuerzo",
                            Description = "Guiso cuyo ingrediente principal son los garbanzos y los secundarios, aunque con gran protagonismo, diversas verduras, carnes y tocino de cerdo con algún embutido.​",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/8.cocido-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5775),
                            Md_uuid = new Guid("a6f7a1ee-82c0-4fed-95c1-72aab59fc6de"),
                            Name = "Cocido Madrileño",
                            Price = 9.9499999999999993,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Cena",
                            Description = "​Porción de masa hecha de una salsa densa como la bechamel y un picadillo de diversos ingredientes, que ha sido rebozada en huevo y pan rallado, y frita en abundante aceite.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/9.croquetas-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5781),
                            Md_uuid = new Guid("eccaa943-c812-4e78-af3c-bb665e0fa072"),
                            Name = "Croquetas",
                            Price = 7.9900000000000002,
                            Tag = "Más vendidos"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Postre",
                            Description = "​Plato hecho de una rebanada de pan (habitualmente de varios días) que es empapada en leche, almíbar o vino y, tras ser rebozada en huevo, se fríe en una sartén con aceite.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/10.torrijas-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5787),
                            Md_uuid = new Guid("a0056dc9-2803-4cc0-ba95-477189aa1d77"),
                            Name = "Torrijas",
                            Price = 6.4500000000000002,
                            Tag = "Mejor valorados"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Postre",
                            Description = "​Tipo de fruta de sartén que se suele servir como dulce navideño o de Semana Santa, típico de Andalucía y otras zonas de España, elaborado con masa de harina, frito en aceite de oliva y pasado por miel.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/11.pestiños-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5795),
                            Md_uuid = new Guid("1b680611-42dc-45f2-a28f-60f16892db7f"),
                            Name = "Pestiños",
                            Price = 5.75,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Desayuno",
                            Description = "​Es una fruta de sartén hecha de agua, harina (de trigo generalmente, aunque puede ser de otro origen), aceite y sal. Pueden tener formas de bastón, en lazos o rulos (espirales).",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/12.churros-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5801),
                            Md_uuid = new Guid("f3c29075-d517-43eb-bcba-93a475d7f548"),
                            Name = "Churros",
                            Price = 3.9900000000000002,
                            Tag = "Más vendidos"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Postre",
                            Description = "​Tipo de fritura de sartén dulce propia de la repostería española realizado a base de harina cocida con leche y azúcar hasta que este preparado espesa, cortándose la masa resultante en porciones que posteriormente se fríen.",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/13.leche-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5807),
                            Md_uuid = new Guid("9228989d-6766-4f53-bbd1-a970cb587989"),
                            Name = "Leche Frita",
                            Price = 4.75,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Postre",
                            Description = "Son una receta dulce propia de Extremadura que se preparan desde Todos los Santos, pasando por Carnaval hasta Semana Santa. Se trata de una receta muy antigua que nos recuerda a las rosquillas por el tipo de masa.​",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/14.huesillos-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5813),
                            Md_uuid = new Guid("30ce20d8-9152-469e-b2bb-4b80a653b3b4"),
                            Name = "Huesillos Extremeños",
                            Price = 3.5,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Bebidas",
                            Description = "​Lata de CocaCola de 33cl. CocaCola Zero (sin azúcar) o CocaCola Original",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/15.cocacola-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5821),
                            Md_uuid = new Guid("854be030-81c1-4163-bbe3-a787d9b8ad19"),
                            Name = "CocaCola",
                            Price = 1.5,
                            Tag = "Más vendidos"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Bebidas",
                            Description = "Lata de Fanta de 33cl. Fanta de naranja o Fanta de limón​",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/16.fanta-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5827),
                            Md_uuid = new Guid("d8c58d8f-aa61-43fe-8110-a710a6b2f732"),
                            Name = "Fanta",
                            Price = 1.5,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Bebidas",
                            Description = "Lata de 7up de 33cl. 7up free (sin azúcar) o 7up original​",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/17.7up-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5833),
                            Md_uuid = new Guid("a30c6836-e360-456f-9256-320b6dad327b"),
                            Name = "7up",
                            Price = 1.5,
                            Tag = "Recomendados"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Bebidas",
                            Description = "​Lata de Cruzcampo de 33cl. Cerveza Pilsen",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/18.cruzcampo-pilsen-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5839),
                            Md_uuid = new Guid("abd5123c-f911-4b3d-9744-4076ffcf7de4"),
                            Name = "Cruzcampo Pilsen",
                            Price = 1.8,
                            Tag = "Más vendidos"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Bebidas",
                            Description = "​Lata de Cruzcampo de 33cl. Cerveza Especial",
                            Image = "https://efooddeliveryimagenes.blob.core.windows.net/efooddelivery-contenedor-imagenes/19.cruzcampo-especial-nobg.png",
                            Md_date = new DateTime(2023, 4, 24, 15, 30, 3, 217, DateTimeKind.Local).AddTicks(5847),
                            Md_uuid = new Guid("dab3e925-2c19-4446-bd68-3393ebd97c76"),
                            Name = "Cruzcampo Especial",
                            Price = 1.8999999999999999,
                            Tag = "Mejor valorados"
                        });
                });

            modelBuilder.Entity("eFoodDelivery_API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("dlk_users", "dlk_efooddelivery_api");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("eFoodDelivery_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("eFoodDelivery_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eFoodDelivery_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("eFoodDelivery_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.CartItem", b =>
                {
                    b.HasOne("eFoodDelivery_API.Entities.Cart", null)
                        .WithMany("CartItemsList")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eFoodDelivery_API.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.Order", b =>
                {
                    b.HasOne("eFoodDelivery_API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.OrderDetails", b =>
                {
                    b.HasOne("eFoodDelivery_API.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eFoodDelivery_API.Entities.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.Cart", b =>
                {
                    b.Navigation("CartItemsList");
                });

            modelBuilder.Entity("eFoodDelivery_API.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
