using Microsoft.AspNetCore.Identity;

namespace eFoodDelivery_API.Models
{
    // ApplicationUser is my own class that represents the UserEntity (IdentityUser autogenerated by .NET)
    // IdentityUser has lot of fields by default, but here we can define more fields to add to the users table in db
    public class ApplicationUser : IdentityUser
    {
        public string Name { get; set; }  // to define a name for the user
        public string Code { get; set; }  // to generate a code for recover password
    }
}
